### ISSUE TITLE
Depend on timidity instead of bundling its source

### ISSUE THREAD

**Issue by candrews** [xbmc/audiodecoder.timidity#12]
Instead of bundling the source in https://github.com/notspiff/audiodecoder.timidity/tree/master/lib/timidity can you instead depend on timidity?

**Comment by notspiff** [comment]
I cannot. Distros in general doesnt provide the library only binary

21. des. 2016 19:03 skrev "Craig Andrews" <notifications@github.com>:

**Comment by AlwinEsch** [comment]
Timidity is only a executable, where is used on Kodi addon as shared library (by few code changes) and can never be present in original as library only.
